# Generated by Django 2.0.5 on 2018-05-25 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('destination', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('type', 'call_id')},
        ),
    ]
